travis:
  secure:
    BINSTAR_TOKEN: M/7A5XHnPbNnTPcxaBkWzdeFEPdZECrOPt4pUNBy1s4FQf9anhhJbjXlnl4QDVy8e7vulmEjfIcAtq6gjtyk+dRVq+hwBDR+GpFNudXO8o86JTssDcR7YklCarKsjiosOPMrqr/MDdXKnAkWu2V5J/e8SaE4dV6kRzGQ1E8suDIMnfJkP/GIBks4IWlQ+wD+9R404VKI4kELn6IzEr/E+UlkKIp4lZnBjKFlLIBkBKStADSLnuphNhah2VoBvjkiSq2KXLcZPwg4/RwOLzmtVguziH1lSc9M+eh2E6Uu8pjt814CKmQtfOQPrCh6LGQAqPUAxpUuH1vGK7yHFR5qcAGIPpQwe2NGlPme8SihiDKjIeEN5OHZqR0QGYYBfKwH3h4CRtnsSFudZqvuHRSQNJX36uoZAxKrVRAa3hhGtKCd3FjD3nAulL9bNQ7Ka2mtpiwurafh63Y+Ca7RbVjxzMvmLNhy2fUydd7zWcubXBYlxeVz72PTgeCTi/ZCxa/K1+23yiMIxzn6gd90i9XkFFnBqmnnQKoYtmGkGlVS/mqhpm7k0VudDKwZtdFynHOxf8/J+T0O0Qn6ZL1NQ+DfzBHRTpqR2KOEJfb0icoxgYIgVF5FU7I7x2W8nBNOEJxlEFkWlWb+l/o5DPlzfYRxJDB/7udB2mOLffR5XI/fqCA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
