travis:
  secure:
    BINSTAR_TOKEN: lQ9tSNJk8veSMtGO7gEgbRRJfMxz2Ar/zX1uqHR9vHVJpxgLUzIJCdqYqpig8es+GSJJa8cMMIYK445UgW3nTVf6wpXK0E+eGCBw56P7CIGoc5H77IwHq3aT6atueH+kQ/9uyXxZmHdZ1eu2vUofnweqVd6wLq/1sxbVA/eaWy0Pf8Q21g0aCHldZ5Nl4MkZBVGp/8ppGDjwjRv3uaMPSfQaWXH6DaczWb5LYFH6QXyPPtvSUpKcEY+P+xNM5PdFqDSIJBoYlyaensgd/deLHks8kAhG6A04IsfzcP2WCvPd4TSSkey2sbpRdXSZuLEdJ+RG8Oiz7H75JSZ8rsC3cyVNWCOg0b617f9fXGlSMSYkYGVMR+nRSuvm53w+Vo+CA6sprL6wsPyCyimi1HYtFUi/H1VpWPfhJPPbDj1ZxjPv+GnU6LVDsazweYla0pyTuUNFjTmG/untPfT+uuA8G/dD3bwlG1JfcRB5kQ4Z2aVmLQ6oyoeRG7uMeKEQdHkY8LT84+GjtkqRfkhQR2noOy/rXv/wcL5t97aAhBBREziecA+w8u8d3g64QU/1/33PiJR6Bg2LQdF0UmLUtL48F64JDFMZzsr1+27kAa8FWR6Y5CXk0vmWGoKbCVMd6eEDFLQkzk+kyiYfEPx960J/fisrjvgeRBT+PmefLHyZp8s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
