travis:
  secure:
    BINSTAR_TOKEN: 2gB/KQelk1ZR2aqwaa8zVXsxijyln9KNxv10btoeNTTQpXYYo5hGCal4htwiMiXL1fAPvUZqrqLf+DcpZD7gD55+K2XVAvTXBXNwchaTuLZCsURRr+DaDh8BRWZAhzdLJ3Jew9OqEd0ZyUXJIPhPAbGwPejH4vEfEUV9/HBmXo1JCeGxyUSeHWO8tqFnu6rXLDN64J+ty9qbpr97yl00EuARW1EDE9021v4UFcNePjdFAYCnhv9OmZL2a8R2J/B34S8bLtt0pysEFmklixypifRu1X2p8jKyvl/halSthmsAkOfHzQz02Lp2FEmwQ9OAQd6tbVTxMp/q+ZfCrQ40Gy3ar/h1uPxcJIPgJEwLhXfcz0wX1QaSACV1smxaIaiTusI6aAx5Gqq+/bDpqf+iNMKx6mF6qvr3SzFjlGx1qLsmMUpRfE+DwyvtOr9GiChYVVBUK9mAyR9Uy4KL4+USYzGThZgIc8UnfHWnka2XLGLT4dfhu5a51jQ++4NmMhz2uoAo9DeNHXhDs1Leut/eH+sQeGOsRn3oOYs5rFF24RbGSsShyHk8cACY004J/RMl/na5MXyXyv9v6ghN1lSuOPARqnSR8T+/9IxqYdpJHL2tXZl3VSpf6RlDjgNKkhDu0IX568EHtYWp3N0ZbPI8lIZlhQziZ6o3gsBYpLPp9Wo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
